Opponent Mode
l1ttleO/ProjectFNF pull request #25
Opened 2021-12-28 07:01 UTC by Gui-iago

hopefully it looks good

2021-12-28 08:36 UTC, l1ttleO requested changes

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
> +					}
create a `char` variable and use it (like in `opponentNoteHit`)

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
> +			if(!opponentChart) {
```suggestion
			else {
```

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
> +					}
```suggestion
				{
					gottaHitNote = !section.mustHitSection;
				}
				else if (songNotes[1] <= 3 && opponentChart)
				{
					gottaHitNote = !section.mustHitSection;
				}
```
indenting?

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
> +		if (opponentChart) char = dad;
should put this before `if(daNote.gfNote)`

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
> +	}
```suggestion
				char.playAnim('sing' + animToPlay, true);
				char.holdTimer = 0;
				if (ClientPrefs.moveCameraInNoteDirection)
					moveCamera(true, animToPlay);
			}
		}
```
indenting??

2021-12-28 08:36 UTC, l1ttleO commented on source/PlayState.hx
>  				boyfriend.playAnim('sing' + singAnimations[Std.int(Math.abs(direction))] + 'miss', true);
create a `char` variable and use it (like in `opponentNoteHit` but without gf)

2022-01-10 06:30 UTC, Gui-iago commented
I did a bunch of mistakes at the end there, but in general it works without any problems, I couldn't really figure out how the health bar worked for PFNF, so I didn't do anything, and reverted back to it's original state, I'm still learning how to code for FNF in general, so hopefully this looks good and someone can fix my dumb mistakes

2022-01-13 14:49 UTC, l1ttleO requested changes
Also delete these files
![image](https://user-images.githubusercontent.com/61277953/149352274-3e54fd72-438a-4e9d-b6c1-5dae970d647f.png)

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +				if (!opponentChart || opponentChart && ClientPrefs.middleScroll) opponentStrums.add(babyArrow);
```suggestion
				if (!opponentChart || ClientPrefs.middleScroll) opponentStrums.add(babyArrow);
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +				if (!opponentChart || opponentChart && ClientPrefs.middleScroll) playerStrums.add(babyArrow);
```suggestion
				if (!opponentChart || ClientPrefs.middleScroll) playerStrums.add(babyArrow);
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +				if (songNotes[1] > 3 && !opponentChart)
```suggestion
				if (songNotes[1] > 3)
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +				else if (songNotes[1] <= 3 && opponentChart)
```suggestion
				else if (opponentChart)
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +					if(opponentChart && !note.gfNote) {
```suggestion
					if(opponentChart) {
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
>  					if(note.gfNote) {
```suggestion
					else if(note.gfNote) {
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +
```suggestion
```

2022-01-13 14:49 UTC, l1ttleO commented on source/PlayState.hx
> +				boyfriend.holdTimer = 0;
```suggestion
				boyfriend.holdTimer = 0;
				if (ClientPrefs.moveCameraInNoteDirection)
					moveCamera(false, animToPlay);
```

2022-01-14 06:08 UTC, l1ttleO approved these changes
Thanks for your contribution

2022-01-14 06:35 UTC, merged